### ISSUE TITLE
Add the ability for the third party notices to include a static set of notices.

### ISSUE THREAD

**Issue by tangollama** [newrelic/newrelic-oss-cli#8]
Relics, see thread https://newrelic.slack.com/archives/C2XN6HL2G/p1593641098309200

- Look for a `THIRD_PARTY_NOTICES_ADDENDUM.md` in the root of the project
- If it's present, include it in the content of the output of `THIRD_PARTY_NOTICES.md`

Feature request by @carlonewrelic

**Comment by carlonewrelic** [comment]
Here is an example of the `THIRD_PARTY_NOTICES_ADDENDUM.md` that I've created for the Node Agent.  I would imagine that we should be able to add multiple licenses to this file and they would be added to the `third_party_manifest.json` and `THIRD_PARTY_NOTICES.md`.
https://github.com/newrelic/node-newrelic/pull/416/files?short_path=2590a69#diff-2590a6993197f4518e856862c0f750a2
Please note that I added a comment to the top of the file indicating why it exists.  We can conform to whatever format you prefer for this file.
For the `THIRD_PARTY_NOTICES.md`, I manually added the additional license language to the file in a new section `additional-licenses`.  What are your thought on that section?  
https://github.com/newrelic/node-newrelic/pull/416/files#diff-b81adcdc0323ca794c275b298f1e7adaR68

**Comment by tangollama** [comment]
Closed by release: https://github.com/newrelic/newrelic-oss-cli/tree/v0.0.3
